Update rogii build scripts
rogii-com/openssl pull request #4
Opened 2021-09-29 11:38 UTC by Shkarlatov

2021-10-01 12:57 UTC, mr-bit requested changes

2021-10-01 12:57 UTC, mr-bit commented on CMakeLists.txt
> +    ${PROJECT_SOURCE_DIR}/rogii/npm/Include.cmake
Unify and add environment.cmake
```
set(
    ROGII_FOLDER_PATH
    "${CMAKE_CURRENT_LIST_DIR}/rogii"
)
include(${ROGII_FOLDER_PATH}/npm/Include.cmake)
include(${ROGII_FOLDER_PATH}/environment.cmake)
```

2021-10-01 12:57 UTC, mr-bit commented on CMakeLists.txt
>          copy
Remove this command, it duplicates copy command from build_common.cmake

2021-10-01 12:57 UTC, mr-bit commented on compile.bat
> +call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 10.0.18362.0 -vcvars_ver=14.27.29110
Remove compile.bat file

2021-10-04 10:08 UTC, mr-bit approved these changes

2021-10-05 05:48 UTC, chak3r approved these changes

2021-10-11 06:39 UTC, merged